name: reviewdog
on: [pull_request]
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: development
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
